const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  SALON_OWNER: "SALON_OWNER",
  RECEPTIONIST: "RECEPTIONIST",
};

const APPOINTMENT_STATUS = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED",
};

const BLOCKING_STATUSES = [
  APPOINTMENT_STATUS.PENDING,
  APPOINTMENT_STATUS.CONFIRMED,
  APPOINTMENT_STATUS.COMPLETED,
];

const SUBSCRIPTION_STATUS = {
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  INACTIVE: "INACTIVE",
};

const SUBSCRIPTION_ACTION = {
  ASSIGN: "ASSIGN",
  RENEW: "RENEW",
  UPGRADE: "UPGRADE",
};

const DEFAULT_OPENING_TIME = "09:00";
const DEFAULT_CLOSING_TIME = "20:00";

module.exports = {
  ROLES,
  APPOINTMENT_STATUS,
  BLOCKING_STATUSES,
  SUBSCRIPTION_STATUS,
  SUBSCRIPTION_ACTION,
  DEFAULT_OPENING_TIME,
  DEFAULT_CLOSING_TIME,
};
